### PR TITLE
build(release process): reviewed release env and releaserc file for extended teams notifications

### PR DESCRIPTION
**Pull request by AsifNawaz-cnic**

### CODE REVIEW

**Review by KaiSchwarz-cnic — APPROVED** [review]

**Comment by KaiSchwarz-cnic** [comment]
@AsifNawaz-cnic There are conflicts to solve :-)

**Comment by AsifNawaz-cnic** [comment]
> @AsifNawaz-cnic There are conflicts to solve :-)

Sorry just overseen, solved the conflicts 🥇

**Comment by KaiSchwarz-cnic** [comment]
we are working together in real time!

**Pull request merged**
